#pragma once

// KernelMemoryLab Protocol 1.0
// All structures are fixed-width, flat, pointer-free, and little-endian.

#define KML_PROTOCOL_VERSION_MAJOR 1u
#define KML_PROTOCOL_VERSION_MINOR 0u

#define KML_DRIVER_VERSION_MAJOR 0u
#define KML_DRIVER_VERSION_MINOR 5u
#define KML_DRIVER_VERSION_BUILD 0u
#define KML_DRIVER_VERSION_REVISION 0u

#define KML_MAX_SINGLE_ITEM_SIZE 4096u
#define KML_MAX_BATCH_ITEMS 128u
#define KML_MAX_BATCH_PAYLOAD_SIZE (KML_MAX_SINGLE_ITEM_SIZE * KML_MAX_BATCH_ITEMS)

#define KML_CAPABILITY_GET_PROTOCOL_VERSION (1ull << 0)
#define KML_CAPABILITY_GET_CAPABILITIES     (1ull << 1)
#define KML_CAPABILITY_PING                 (1ull << 2)
#define KML_CAPABILITY_READ_SINGLE          (1ull << 8)
#define KML_CAPABILITY_WRITE_SINGLE         (1ull << 9)
#define KML_CAPABILITY_READ_BATCH           (1ull << 10)
#define KML_CAPABILITY_WRITE_BATCH          (1ull << 11)

#define KML_PHASE02_CAPABILITIES \
    (KML_CAPABILITY_GET_PROTOCOL_VERSION | \
     KML_CAPABILITY_GET_CAPABILITIES | \
     KML_CAPABILITY_PING)

#define KML_PHASE04_CAPABILITIES \
    (KML_PHASE02_CAPABILITIES | \
     KML_CAPABILITY_READ_SINGLE | \
     KML_CAPABILITY_WRITE_SINGLE)

#define KML_PHASE05_CAPABILITIES \
    (KML_PHASE04_CAPABILITIES | \
     KML_CAPABILITY_READ_BATCH | \
     KML_CAPABILITY_WRITE_BATCH)

#define KML_IOCTL_FUNCTION_GET_PROTOCOL_VERSION 0x800u
#define KML_IOCTL_FUNCTION_GET_CAPABILITIES     0x801u
#define KML_IOCTL_FUNCTION_PING                 0x802u

// Reserved for future phases. Phase 02 does not implement these IOCTLs.
#define KML_IOCTL_FUNCTION_READ_SINGLE  0x810u
#define KML_IOCTL_FUNCTION_WRITE_SINGLE 0x811u
#define KML_IOCTL_FUNCTION_READ_BATCH   0x812u
#define KML_IOCTL_FUNCTION_WRITE_BATCH  0x813u

#define IOCTL_KML_GET_PROTOCOL_VERSION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, KML_IOCTL_FUNCTION_GET_PROTOCOL_VERSION, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_KML_GET_CAPABILITIES \
    CTL_CODE(FILE_DEVICE_UNKNOWN, KML_IOCTL_FUNCTION_GET_CAPABILITIES, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_KML_PING \
    CTL_CODE(FILE_DEVICE_UNKNOWN, KML_IOCTL_FUNCTION_PING, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define IOCTL_KML_READ_SINGLE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, KML_IOCTL_FUNCTION_READ_SINGLE, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_KML_WRITE_SINGLE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, KML_IOCTL_FUNCTION_WRITE_SINGLE, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_KML_READ_BATCH \
    CTL_CODE(FILE_DEVICE_UNKNOWN, KML_IOCTL_FUNCTION_READ_BATCH, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_KML_WRITE_BATCH \
    CTL_CODE(FILE_DEVICE_UNKNOWN, KML_IOCTL_FUNCTION_WRITE_BATCH, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

typedef enum _KML_OPERATION_STATUS {
    KmlOperationSuccess = 0,
    KmlOperationProtocolMismatch = 1,
    KmlOperationInvalidStructureSize = 2,
    KmlOperationInvalidFlags = 3,
    KmlOperationInvalidReservedField = 4,
    KmlOperationUnsupportedOperation = 5,
    KmlOperationBufferTooSmall = 6,
    KmlOperationInternalError = 7,
    KmlOperationInvalidRequest = 8,
    KmlOperationInvalidPid = 9,
    KmlOperationTargetNotFound = 10,
    KmlOperationTargetNotAllowed = 11,
    KmlOperationInvalidAddress = 12,
    KmlOperationInvalidSize = 13,
    KmlOperationAddressRangeOverflow = 14,
    KmlOperationKernelRangeDenied = 15,
    KmlOperationMemoryNotAccessible = 16,
    KmlOperationPartialTransfer = 17,
    KmlOperationTargetExited = 18,
    KmlOperationInvalidItemCount = 19,
    KmlOperationInvalidOffset = 20,
    KmlOperationAggregateLimitExceeded = 21,
    KmlOperationAllItemsFailed = 22
} KML_OPERATION_STATUS;

#pragma pack(push, 1)

typedef struct _KML_PROTOCOL_VERSION {
    UINT16 Major;
    UINT16 Minor;
} KML_PROTOCOL_VERSION, *PKML_PROTOCOL_VERSION;

typedef struct _KML_DRIVER_VERSION {
    UINT16 Major;
    UINT16 Minor;
    UINT16 Build;
    UINT16 Revision;
} KML_DRIVER_VERSION, *PKML_DRIVER_VERSION;

typedef struct _KML_COMMON_REQUEST_HEADER {
    KML_PROTOCOL_VERSION ProtocolVersion;
    UINT32 StructureSize;
    UINT32 Flags;
    UINT32 Reserved;
} KML_COMMON_REQUEST_HEADER, *PKML_COMMON_REQUEST_HEADER;

typedef struct _KML_COMMON_RESPONSE_HEADER {
    KML_PROTOCOL_VERSION ProtocolVersion;
    UINT32 OperationStatus;
    UINT32 BytesProcessed;
    UINT32 DetailStatus;
} KML_COMMON_RESPONSE_HEADER, *PKML_COMMON_RESPONSE_HEADER;

typedef struct _KML_GET_PROTOCOL_VERSION_REQUEST {
    KML_COMMON_REQUEST_HEADER Header;
} KML_GET_PROTOCOL_VERSION_REQUEST, *PKML_GET_PROTOCOL_VERSION_REQUEST;

typedef struct _KML_GET_PROTOCOL_VERSION_RESPONSE {
    KML_COMMON_RESPONSE_HEADER Header;
} KML_GET_PROTOCOL_VERSION_RESPONSE, *PKML_GET_PROTOCOL_VERSION_RESPONSE;

typedef struct _KML_GET_CAPABILITIES_REQUEST {
    KML_COMMON_REQUEST_HEADER Header;
} KML_GET_CAPABILITIES_REQUEST, *PKML_GET_CAPABILITIES_REQUEST;

typedef struct _KML_GET_CAPABILITIES_RESPONSE {
    KML_COMMON_RESPONSE_HEADER Header;
    UINT64 Capabilities;
    UINT32 MaxSingleItemSize;
    UINT32 MaxBatchItems;
    UINT32 MaxBatchPayloadSize;
    UINT32 Reserved;
} KML_GET_CAPABILITIES_RESPONSE, *PKML_GET_CAPABILITIES_RESPONSE;

typedef struct _KML_PING_REQUEST {
    KML_COMMON_REQUEST_HEADER Header;
    UINT64 Token;
} KML_PING_REQUEST, *PKML_PING_REQUEST;

typedef struct _KML_PING_RESPONSE {
    KML_COMMON_RESPONSE_HEADER Header;
    KML_DRIVER_VERSION DriverVersion;
    UINT64 Capabilities;
    UINT64 EchoToken;
} KML_PING_RESPONSE, *PKML_PING_RESPONSE;

typedef struct _KML_READ_SINGLE_REQUEST {
    KML_COMMON_REQUEST_HEADER Header;
    UINT32 TargetProcessId;
    UINT32 Size;
    UINT64 Address;
} KML_READ_SINGLE_REQUEST, *PKML_READ_SINGLE_REQUEST;

typedef struct _KML_READ_SINGLE_RESPONSE {
    KML_COMMON_RESPONSE_HEADER Header;
    UCHAR Data[ANYSIZE_ARRAY];
} KML_READ_SINGLE_RESPONSE, *PKML_READ_SINGLE_RESPONSE;

typedef struct _KML_WRITE_SINGLE_REQUEST {
    KML_COMMON_REQUEST_HEADER Header;
    UINT32 TargetProcessId;
    UINT32 Size;
    UINT64 Address;
    UCHAR Data[ANYSIZE_ARRAY];
} KML_WRITE_SINGLE_REQUEST, *PKML_WRITE_SINGLE_REQUEST;

typedef struct _KML_WRITE_SINGLE_RESPONSE {
    KML_COMMON_RESPONSE_HEADER Header;
} KML_WRITE_SINGLE_RESPONSE, *PKML_WRITE_SINGLE_RESPONSE;

typedef struct _KML_READ_BATCH_REQUEST_HEADER {
    KML_COMMON_REQUEST_HEADER Header;
    UINT32 TargetProcessId;
    UINT32 ItemCount;
    UINT32 ItemsOffset;
    UINT32 Reserved;
} KML_READ_BATCH_REQUEST_HEADER, *PKML_READ_BATCH_REQUEST_HEADER;

typedef struct _KML_READ_BATCH_ITEM {
    UINT64 Address;
    UINT32 Size;
    UINT32 ResultOffset;
} KML_READ_BATCH_ITEM, *PKML_READ_BATCH_ITEM;

typedef struct _KML_READ_BATCH_RESPONSE_HEADER {
    KML_COMMON_RESPONSE_HEADER Header;
    UINT32 ItemCount;
    UINT32 ResultsOffset;
    UINT32 DataOffset;
    UINT32 DataSize;
} KML_READ_BATCH_RESPONSE_HEADER, *PKML_READ_BATCH_RESPONSE_HEADER;

typedef struct _KML_WRITE_BATCH_REQUEST_HEADER {
    KML_COMMON_REQUEST_HEADER Header;
    UINT32 TargetProcessId;
    UINT32 ItemCount;
    UINT32 ItemsOffset;
    UINT32 DataOffset;
    UINT32 DataSize;
    UINT32 Reserved;
} KML_WRITE_BATCH_REQUEST_HEADER, *PKML_WRITE_BATCH_REQUEST_HEADER;

typedef struct _KML_WRITE_BATCH_ITEM {
    UINT64 Address;
    UINT32 Size;
    UINT32 DataOffset;
} KML_WRITE_BATCH_ITEM, *PKML_WRITE_BATCH_ITEM;

typedef struct _KML_WRITE_BATCH_RESPONSE_HEADER {
    KML_COMMON_RESPONSE_HEADER Header;
    UINT32 ItemCount;
    UINT32 ResultsOffset;
} KML_WRITE_BATCH_RESPONSE_HEADER, *PKML_WRITE_BATCH_RESPONSE_HEADER;

typedef struct _KML_BATCH_ITEM_RESULT {
    UINT32 OperationStatus;
    UINT32 BytesProcessed;
    UINT32 DataOffset;
    UINT32 RequestedSize;
    UINT32 DetailStatus;
    UINT32 Reserved;
} KML_BATCH_ITEM_RESULT, *PKML_BATCH_ITEM_RESULT;

#pragma pack(pop)

#define KML_READ_SINGLE_RESPONSE_HEADER_SIZE \
    FIELD_OFFSET(KML_READ_SINGLE_RESPONSE, Data)
#define KML_WRITE_SINGLE_REQUEST_HEADER_SIZE \
    FIELD_OFFSET(KML_WRITE_SINGLE_REQUEST, Data)

